// Service catalogue shown on the home and services pages.

export const services = [
  {
    title: "Transportation Engineering & Planning",
    titleAr: "هندسة وتخطيط النقل",
    desc: "Advanced transport planning, mobility systems, and infrastructure strategies.",
    descAr: "تخطيط النقل، أنظمة الحركة، واستراتيجيات البنية التحتية.",
    img: "/images/transport.webp",
    details: [
      "Transport master plans and strategic mobility studies.",
      "Travel demand forecasting and network assessment.",
      "Public transport integration and multimodal planning.",
      "Accessibility, mobility, and urban transport policy support.",
    ],
    detailsAr: [
      "إعداد مخططات النقل الرئيسية والدراسات الاستراتيجية للحركة.",
      "التنبؤ بالطلب المروري وتقييم شبكات النقل.",
      "دمج النقل العام والتخطيط متعدد الوسائط.",
      "دعم سياسات الوصول والحركة والنقل الحضري.",
    ],
  },
  {
    title: "Traffic Engineering & Impact Studies",
    titleAr: "هندسة المرور ودراسات الأثر المروري",
    desc: "Comprehensive traffic analysis, modeling, and impact assessment.",
    descAr: "تحليل مروري شامل، نمذجة، ودراسات أثر مروري.",
    img: "/images/traffic.webp",
    details: [
      "Traffic impact assessments for developments and infrastructure projects.",
      "Intersection capacity and level-of-service analysis.",
      "Traffic surveys, turning counts, queue and delay studies.",
      "Signalized intersections, roundabouts, and access management review.",
    ],
    detailsAr: [
      "دراسات الأثر المروري للمشاريع التطويرية والبنية التحتية.",
      "تحليل سعة التقاطعات ومستوى الخدمة.",
      "العدّ المروري، حركات الالتفاف، الطوابير، والتأخير.",
      "مراجعة الإشارات المرورية والدوارات وإدارة المداخل.",
    ],
  },
  {
    title: "Roads, Highways & Corridors",
    titleAr: "الطرق والطرق السريعة والممرات الدولية",
    desc: "Design and planning of road networks and international corridors.",
    descAr: "تخطيط وتصميم شبكات الطرق والممرات الدولية.",
    img: "/images/road.webp",
    details: [
      "Road network planning and geometric design review.",
      "Highway corridors and strategic route studies.",
      "Pavement planning and road infrastructure integration.",
      "Access roads, junctions, and corridor development studies.",
    ],
    detailsAr: [
      "تخطيط شبكات الطرق ومراجعة التصميم الهندسي.",
      "دراسات الطرق السريعة والممرات الاستراتيجية.",
      "تخطيط الرصف وربط البنية التحتية للطرق.",
      "دراسات المداخل والتقاطعات وتطوير الممرات.",
    ],
  },
  {
    title: "Ports & Maritime Transport",
    titleAr: "الموانئ والنقل البحري",
    desc: "Specialized studies supporting maritime infrastructure and logistics.",
    descAr: "دراسات متخصصة للبنية التحتية البحرية واللوجستية.",
    img: "/images/port.webp",
    details: [
      "Port access and freight movement studies.",
      "Logistics interface between ports, roads, and industrial areas.",
      "Heavy vehicle circulation and terminal connectivity.",
      "Maritime transport planning and cargo movement assessment.",
    ],
    detailsAr: [
      "دراسات مداخل الموانئ وحركة البضائع.",
      "الربط اللوجستي بين الموانئ والطرق والمناطق الصناعية.",
      "تحليل حركة الشاحنات الثقيلة وربط المحطات.",
      "تخطيط النقل البحري وتقييم حركة الشحن.",
    ],
  },
  {
    title: "Railway Planning",
    titleAr: "تخطيط السكك الحديدية",
    desc: "Rail systems planning, alignment design, and operational studies.",
    descAr: "تخطيط أنظمة السكك الحديدية والمسارات والتشغيل.",
    img: "/images/railway.webp",
    details: [
      "Railway corridor planning and route assessment.",
      "Passenger and freight rail system studies.",
      "Station access and intermodal connectivity.",
      "Integration of railway systems with ports, roads, and urban areas.",
    ],
    detailsAr: [
      "تخطيط ممرات السكك الحديدية وتقييم المسارات.",
      "دراسات نقل الركاب والبضائع بالسكك الحديدية.",
      "دراسة الوصول للمحطات والربط متعدد الوسائط.",
      "دمج السكك الحديدية مع الموانئ والطرق والمناطق الحضرية.",
    ],
  },
  {
    title: "Airport & Airside Infrastructure",
    titleAr: "المطارات والبنية التحتية الجوية",
    desc: "Airport planning, apron design, and aviation infrastructure.",
    descAr: "تخطيط المطارات والساحات والبنية التحتية الجوية.",
    img: "/images/airport.webp",
    details: [
      "Airport access and landside/airside circulation studies.",
      "Apron, taxiway, and operational infrastructure planning.",
      "Passenger, cargo, and service movement assessment.",
      "Technical support for aviation-related infrastructure projects.",
    ],
    detailsAr: [
      "دراسات الوصول للمطارات وحركة الجانب الأرضي والجوي.",
      "تخطيط الساحات وممرات الطائرات والبنية التشغيلية.",
      "تقييم حركة الركاب والبضائع والخدمات.",
      "الدعم الفني لمشاريع البنية التحتية المرتبطة بالطيران.",
    ],
  },
  {
    title: "Traffic Simulation & Modeling",
    titleAr: "المحاكاة والنمذجة المرورية",
    desc: "Advanced simulation using PTV VISSIM, SIDRA, SUMO, and other platforms.",
    descAr: "محاكاة مرورية متقدمة باستخدام VISSIM وSIDRA وSUMO وغيرها.",
    img: "/images/traffic-simulation.webp",
    details: [
      "Microscopic and macroscopic traffic simulation.",
      "PTV VISSIM, SIDRA, SUMO, Synchro and similar platforms.",
      "Signal optimization and operational scenario testing.",
      "Congestion analysis, queue assessment, and visual simulation outputs.",
    ],
    detailsAr: [
      "محاكاة مرورية مجهرية وكلية للظواهر المرورية.",
      "استخدام برامج مثل PTV VISSIM وSIDRA وSUMO وSynchro.",
      "تحسين الإشارات واختبار السيناريوهات التشغيلية.",
      "تحليل الازدحام والطوابير وإخراج نماذج مرئية للمحاكاة.",
    ],
  },
  {
    title: "Infrastructure & GIS Integration",
    titleAr: "البنية التحتية والتكامل مع GIS",
    desc: "Integrated infrastructure solutions fully connected with GIS systems.",
    descAr: "حلول بنية تحتية متكاملة مرتبطة بأنظمة GIS.",
    img: "/images/infrastructure-gis.webp",
    details: [
      "Stormwater drainage, sewer networks, and road infrastructure planning.",
      "GIS-based infrastructure mapping and spatial analysis.",
      "Utility coordination and infrastructure database development.",
      "Integration of civil engineering design outputs with digital maps.",
    ],
    detailsAr: [
      "تخطيط شبكات تصريف مياه الأمطار والصرف الصحي والطرق.",
      "إعداد خرائط البنية التحتية والتحليل المكاني باستخدام GIS.",
      "تنسيق المرافق وإعداد قواعد بيانات البنية التحتية.",
      "ربط مخرجات التصميم المدني بالخرائط الرقمية.",
    ],
  },
  {
    title: "Tendering, RFP & Project Documentation",
    titleAr: "إعداد مستندات الطرح والعروض الفنية",
    desc: "Preparation of RFPs, tender documents, BOQs, method statements, HSE, QA/QC, and project schedules.",
    descAr:
      "إعداد مستندات الطرح، عروض التقديم، جداول الكميات، أساليب التنفيذ، خطط السلامة والجودة، والجداول الزمنية.",
    img: "/images/tender-documents.webp",
    details: [
      "Preparation of Request for Proposal (RFP), tender documents, and instructions to bidders.",
      "Preparation of Bills of Quantities (BOQ), quantity take-off, measurement sheets, and pricing schedules.",
      "Preparation of technical proposals, project execution methodology, method statements, and work procedures.",
      "Preparation of HSE plans, risk assessments, job safety analysis, and site safety documentation.",
      "Preparation of QA/QC plans, inspection and test plans (ITP), checklists, material submittals, and quality documentation.",
      "Preparation of project schedules using Primavera P6 and Microsoft Project.",
      "Baseline programs, activity sequencing, resource loading, cash flow planning, and progress monitoring reports.",
      "Tender review, clarification registers, compliance matrices, and technical-commercial submission support.",
    ],
    detailsAr: [
      "إعداد طلبات تقديم العروض RFP ومستندات الطرح وتعليمات مقدمي العروض.",
      "إعداد جداول الكميات BOQ وأعمال الحصر والكشف والقياس وجداول التسعير.",
      "إعداد العروض الفنية ومنهجيات التنفيذ وأساليب العمل والإجراءات التنفيذية.",
      "إعداد خطط الصحة والسلامة والبيئة HSE وتقييم المخاطر وتحليل السلامة للأنشطة والمستندات الخاصة بالموقع.",
      "إعداد خطط الجودة QA/QC وخطط الفحص والاختبار ITP ونماذج التفتيش واعتمادات المواد ومستندات ضبط الجودة.",
      "إعداد الجداول الزمنية للمشاريع باستخدام Primavera P6 و Microsoft Project.",
      "إعداد البرامج الزمنية الأساسية وتسلسل الأنشطة وتحميل الموارد والتدفقات النقدية وتقارير متابعة التقدم.",
      "مراجعة مستندات المناقصات، إعداد سجل الاستفسارات، مصفوفة المطابقة، ودعم تجهيز العرض الفني والمالي.",
    ],
  },
  {
    title: "Training & Capacity Building",
    titleAr: "التدريب وبناء القدرات",
    desc: "Professional engineering and technical training programs.",
    descAr: "برامج تدريب هندسية وفنية احترافية.",
    img: "/images/training.webp",
    details: [
      "Training in GIS, AutoCAD, Civil 3D, and surveying applications.",
      "Transportation engineering and traffic planning courses.",
      "Traffic modeling software training including VISSIM, SIDRA, and SUMO.",
      "Practical workshops based on real engineering projects.",
    ],
    detailsAr: [
      "دورات في GIS وAutoCAD وCivil 3D وتطبيقات الرفع المساحي.",
      "دورات في هندسة وتخطيط النقل والتحليل المروري.",
      "تدريب على برامج النمذجة المرورية مثل VISSIM وSIDRA وSUMO.",
      "ورش عملية مبنية على مشاريع هندسية واقعية.",
    ],
  },
  {
    title: "Building & Structural Engineering",
    titleAr: "تصميم المباني والمنشآت",
    desc: "Design and technical studies for buildings and structural systems.",
    descAr: "تصميم ودراسات فنية للمباني والأنظمة الإنشائية.",
    img: "/images/building.webp",
    details: [
      "Conceptual and detailed design support for buildings and civil structures.",
      "Reinforced concrete and steel structure design coordination.",
      "Structural review, quantity assessment, and technical documentation.",
      "Integration with site development, roads, utilities, and infrastructure works.",
    ],
    detailsAr: [
      "دعم التصميم الابتدائي والتفصيلي للمباني والمنشآت المدنية.",
      "تنسيق تصميم المنشآت الخرسانية والمعدنية.",
      "المراجعة الإنشائية وحصر الكميات وإعداد المستندات الفنية.",
      "الربط مع أعمال الموقع والطرق والمرافق والبنية التحتية.",
    ],
  },
];

export const contact = {
  phones: [
    { display: "+218 91 405 4929", tel: "+218914054929" },
    { display: "+218 91 571 8567", tel: "+218915718567" },
  ],
  email: "info@sudaf.ly",
  studiesEmail: "radwan@sudaf.ly",
  mapUrl: "https://maps.app.goo.gl/wbtTLSKjN8kTN2269",
};
